### ISSUE TITLE
warnings when compiling

### ISSUE THREAD

**Issue by stephens999** [stephens999/ashr#1]
MixSquarem.cpp:55:12: warning: unused variable 'kr' [-Wunused-variable]
    double kr=control["kr"];
           ^
MixSquarem.cpp:66:20: warning: unused variable 'leval' [-Wunused-variable]
    int iter,feval,leval;
                   ^
MixSquarem.cpp:212:9: warning: unused variable 'n' [-Wunused-variable]
    int n=matrix_lik.nrow(), k=matrix_lik.ncol(),niter;

**Comment by daichaoxing** [comment]
redundant variables removed.
