### ISSUE TITLE
implement plot method for classes normalmix, unimix, etc?

### ISSUE THREAD

**Issue by willwerscheid** [stephens999/ashr#119]
It'd be nice to be able to plot the CDF of a mixture distribution by calling "plot" on the mixture object (i.e., `plot(g)`).

**Comment by stephens999** [comment]
Does cdf.ash help? Or you know about that already?

**Comment by willwerscheid** [comment]
I was thinking methods for the unimix and normalmix classes since we use them in other packages (ebnm, flashr, etc).

**Comment by willwerscheid** [comment]
I guess we have `mixcdf` for those classes. Are you opposed to implementing `plot` on top of that?

**Comment by willwerscheid** [comment]
Looks like `comp_cdf` still needs to be implemented for `unimix`

**Comment by stephens999** [comment]
it's there: comp_cdf.unimix = function(m,y,lower.tail=TRUE){
  vapply(y,stats::punif,m$a,min=m$a,max=m$b,lower.tail)
}

**Comment by willwerscheid** [comment]
Oh you're right. Not sure how I missed that. I guess you can do a one-line thing like `curve(mixcdf(g, x), from = from, to = to)`, so no need for a `plot` method. I will close this issue.
