### ISSUE TITLE
submit latest version to CRAN?

### ISSUE THREAD

**Issue by jakejh** [stephens999/ashr#127]
I have an R package that I'd like to submit to CRAN and that depends on ashr 2.2-51, which is only on GitHub. Would you be willing to submit 2.2-51 to CRAN? Thanks!

**Comment by pcarbo** [comment]
@jakejh Yes we can update `ashr` on CRAN. Can I ask what package this is?

**Comment by jakejh** [comment]
Sweet, you sure can!

https://limorhyde2.hugheylab.org/

**Comment by pcarbo** [comment]
@jakejh I've made a few small improvements to ashr. Can you please make sure that your package still works with the latest version of ashr, and if it looks okay, I will resubmit to CRAN.

**Comment by jakejh** [comment]
I just checked, and it looks good on my end. `limorhyde` only uses `ashr` indirectly via `mashr`. Thanks @pcarbo!
