### ISSUE TITLE
Many warnings of singular system in R 4.2

### ISSUE THREAD

**Issue by frederikziebell** [stephens999/ashr#131]
As of R4.2, the following code
```
beta = c(rep(0,100),rnorm(100))
sebetahat = abs(rnorm(200,0,1))
betahat = rnorm(200,beta,sebetahat)
beta.ash = ash(betahat, sebetahat)
```
results in many warnings like these: 
`warning: solve(): system is singular (rcond: 2.12669e-17); attempting approx solution`.

**Comment by pcarbo** [comment]
@frederikziebell Thanks for reporting this. This is actually a problem with mixsqp. Can you please try installing the new [mixsqp](https://github.com/stephenslab/mixsqp) and let me know if the warnings go away?

**Comment by frederikziebell** [comment]
This is working without warnings, thanks!
