### ISSUE TITLE
Default Prior is Described Incorrectly in Documentation

### ISSUE THREAD

**Issue by eweine** [stephens999/ashr#136]
In the documentation for `ash` the entry for prior indicates that it defaults to the uniform. However, I was suspicious of this because the first entry in the default parameters list is `"nullbiased"`. Indeed, I confirmed that `nullbiased` is actually the prior. This can be seen with the code below:

```r
set.seed(1)
x <- c(rnorm(100, 0, 1), rep(0, 100))
y <- x + rnorm(200)
ash_fit_default <- ashr::ash(y, rep(1, 200))
ash_fit_unif <- ashr::ash(y, rep(1, 200), prior = "uniform")
ash_fit_nullbiased <- ashr::ash(y, rep(1, 200), prior = "nullbiased")
```

**Comment by pcarbo** [comment]
The convention in R is that the default is the first setting in the list, so we don't actually need to say explicitly:

```r
prior = c("nullbiased", "uniform", "unit")
```
