### ISSUE TITLE
PosteriorMean can be infinity?

### ISSUE THREAD

**Issue by mengyin** [stephens999/ashr#20]
When I tried ash with "df=..." option on this example (data here: https://www.dropbox.com/s/d2n9lxzxtir95nh/eg.Rdata?dl=0),  the "PosteriorMean" in ash object included a few infinities. The corresponding betahat's were indeed quite large (compared to the other betahat's, yet the absolute values were no more than 2), but I guess it's still weird that their posterior means are infinities. 

> load("eg.Rdata")
> test=ash(betahat,sebetahat,df=df)
> sum(test$PosteriorMean==Inf)
[1] 3

If we don't use the "df=..." option, then the posterior means will be fine. I guess there might be some numerical issues when computing the mean of truncated t distribution?

**Comment by stephens999** [comment]
I get warnings: Warning messages:
1: In genhypergeo_series(U, L, z, tol = tol, maxiter = maxiter, check_mod = check_mod,  :
  series not converged
2: In genhypergeo_series(U, L, z, tol = tol, maxiter = maxiter, check_mod = check_mod,  :
  series not converged
3: In GCF(a = -alpha, b = 1 + alpha, tol = tol) :
  Continued fraction not converged
4: In sqrt(postmean2(m, betahat, sebetahat, v) - postmean(m, betahat,  :
  NaNs produced
so seems to be problem with that...

**Comment by mengyin** [comment]
It seems fixed by https://github.com/stephens999/ashr/commit/d86031e670c9e470de194691c5ee972ae0929c88
