### ISSUE TITLE
Request to Export Functions

### ISSUE THREAD

**Issue by dcgerard** [stephens999/ashr#36]
I use the following functions in my [vicar](https://github.com/dcgerard/vicar) package:

`calc_lfdr`, `calc_lfsr`, `calc_np`, `calc_pm`, `calc_pp`, `calc_psd`, `calc_qvalue`, `calc_svalue`, and `estimate_mixprop`.

Since these functions aren't exported in ashr (the general branch), my CRAN checks throw me a note. Could you export these functions? It's not a big deal if you prefer not to, though, as I can just copy and paste the functions for my package.

**Comment by dcgerard** [comment]
I just saw the `fixg` option in `ashr.workhose`, so all I really need is for `estimate_mixprop` to be exported.

**Comment by stephens999** [comment]
i just pushed a change that now exports estimate_mixprop (general branch)
