### ISSUE TITLE
IP optimization error from ashr "general" branch

### ISSUE THREAD

**Issue by pcarbo** [stephens999/ashr#41]
Without the `REBayes` package, `ash` runs successfully (see `ash/analysis/adaptive_shrinkage.Rmd`):

```
R> beta.spiky.ash = ash(sim.spiky$input$betahat,s)                             
Due to absence of package REBayes, switching to EM algorithm
```

However, when I install the `REBayes` package, I get the following error:

```
R> install.packages("REBayes")
R> beta.spiky.ash = ash(sim.spiky$input$betahat,s)
Error in t(A) %*% (f * d) : non-conformable arguments
```

The error appears to be cropping up in a call to the `KWDual` function in the `REBayes` package. Has anyone gotten this error before? Any ideas why this may be occurring?

Note I get the same error in the "master" branch version. Also note that this works fine:
`beta.spiky.ash = ash(sim.spiky$input$betahat,s,optmethod = "cxxMixSquarem")`

**Comment by stephens999** [comment]
i was not able to reproduce this, although I do think i may recall having seen this error in the past.

**Comment by stephens999** [comment]
can you try:  
set.seed(102)
  y <- c(rep(0,800), rnorm(200, 2)) + rnorm(1000)
  z <- REBayes::GLmix(y)

**Comment by stephens999** [comment]
for future, recording Peter's response here: 
pcarbo [12:36 AM]  
I just tried the code above (`set.seed(102) ...`) and I got the same error:
`Error in t(A) %*% (f * d) : non-conformable arguments`

.. so problem is in REBayes

**Comment by pcarbo** [comment]
With a clear mind, the solution turned out to be straightforward: I was missing the MOSEK license file (confusingly license.pdf is not the license!).

**Comment by stephens999** [comment]
i'd like to reopen this as it comes up so often: we should have a try() around the REBayes call, and point the user to this issue if it fails.

**Comment by pcarbo** [comment]
Good idea.

**Comment by pcarbo** [comment]
I think we have already addressed this issue.
