### ISSUE TITLE
Problems with small sebetahat

### ISSUE THREAD

**Issue by dcgerard** [stephens999/ashr#48]
Description
===========

I seem to be getting new errors when the standard deviations are small. However, they aren't really all *that* small.

Example Data and Error
======================

``` r
library(ashr)
betahat   <- c(-2.2, -1.2, 1.3, -1.8, 1.5, 0.9, 1.6, -2, 0.6, 1.1)
sebetahat <- c(0.65, 0.95, 0.32, 0.41, 0.1, 0.17, 0.59, 0.49, 0.51, 0.47)
aout      <- ashr::ash.workhorse(betahat = betahat, sebetahat = sebetahat)
```

    ## Warning in min(f): no non-missing arguments to min; returning Inf

    ## Error in t(A) %*% (f * d): non-conformable arguments

Error goes away for much larger sd

``` r
aout <- ashr::ash.workhorse(betahat = betahat, sebetahat = sebetahat + 1)
```

Generally, problem seems to be small SD

``` r
set.seed(4235)
aout <- ashr::ash.workhorse(betahat = rnorm(5), sebetahat = rep(0.5, 5))
```

    ## Warning in min(f): no non-missing arguments to min; returning Inf

    ## Error in t(A) %*% (f * d): non-conformable arguments

``` r
sessionInfo()
```

    ## R version 3.3.2 (2016-10-31)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 14.04.5 LTS
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] ashr_2.0.4
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.8       knitr_1.15        magrittr_1.5     
    ##  [4] REBayes_0.73      MASS_7.3-45       doParallel_1.0.10
    ##  [7] pscl_1.4.9        SQUAREM_2016.8-2  lattice_0.20-34  
    ## [10] foreach_1.4.3     stringr_1.1.0     tools_3.3.2      
    ## [13] parallel_3.3.2    grid_3.3.2        htmltools_0.3.5  
    ## [16] iterators_1.0.8   yaml_2.1.14       assertthat_0.1   
    ## [19] digest_0.6.10     tibble_1.2        Matrix_1.2-7.1   
    ## [22] codetools_0.2-15  evaluate_0.10     rmarkdown_1.1    
    ## [25] stringi_1.1.2     Rmosek_7.1.3      truncnorm_1.0-7

**Comment by stephens999** [comment]
Not sure but that error you are seeing is associated with out of date mosek licence. It lasts one year and you have to renew. Any chance that is it? (Not sure why it would not happen sometimes though...)

**Comment by stephens999** [comment]
See #41

**Comment by dcgerard** [comment]
That seems to be it, when I set `optmethod = "mixEM"` it works fine.

I think it "works" for larger standard errors because ash first checks at the all-null setting then doesn't run Mosek if the all-null setting is optimal.

``` r
library(ashr)
betahat   <- c(-2.2, -1.2, 1.3, -1.8, 1.5, 0.9, 1.6, -2, 0.6, 1.1)
sebetahat <- c(0.65, 0.95, 0.32, 0.41, 0.1, 0.17, 0.59, 0.49, 0.51, 0.47)
aout      <- ashr::ash.workhorse(betahat = betahat, sebetahat = sebetahat,
                                 optmethod = "mixEM")
aout
```

    ## $pi
    ##  [1] 5.567e-01 3.937e-11 3.935e-11 3.930e-11 3.920e-11 3.901e-11 3.863e-11
    ##  [8] 3.786e-11 3.631e-11 3.316e-11 2.675e-11 1.429e-11 0.000e+00 1.760e-10
    ## [15] 8.621e-11 0.000e+00 0.000e+00 4.433e-01 1.779e-07 0.000e+00
    ## 
    ## $a
    ##  [1]  0.00000 -0.00821 -0.01161 -0.01642 -0.02322 -0.03284 -0.04644
    ##  [8] -0.06568 -0.09289 -0.13136 -0.18577 -0.26272 -0.37155 -0.52545
    ## [15] -0.74309 -1.05089 -1.48619 -2.10178 -2.97237 -4.20357
    ## 
    ## $b
    ##  [1] 0.00000 0.00821 0.01161 0.01642 0.02322 0.03284 0.04644 0.06568
    ##  [9] 0.09289 0.13136 0.18577 0.26272 0.37155 0.52545 0.74309 1.05089
    ## [17] 1.48619 2.10178 2.97237 4.20357
    ## 
    ## attr(,"row.names")
    ##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
    ## attr(,"class")
    ## [1] "unimix"
    ## [1] "Ash object has elements: "
    ## [1] "fitted_g" "loglik"   "logLR"    "data"     "result"
