### ISSUE TITLE
Warnings when using ash(..., df=..., ...)?

### ISSUE THREAD

**Issue by mengyin** [stephens999/ashr#5]
There are such warnings when using the "df=..." option of function ash().

> test=ash(betahat=rnorm(100,0,1),sebetahat=rep(1,100),df=50)
Warning messages:
1: In if (a == b) { :
  the condition has length > 1 and only the first element will be used
2: In if (a == b) { :
  the condition has length > 1 and only the first element will be used
3: In if (a == b) { :
  the condition has length > 1 and only the first element will be used

**Comment by stephens999** [comment]
I think i fixed this now. please let me know if you see unexpected behaviour
