### ISSUE TITLE
rename likelihood functions

### ISSUE THREAD

**Issue by pcarbo** [stephens999/ashr#51]
we should rename all the likelihoods `lik_xxx` instead of `xxx_lik`. This would allow a user to easily see all the likelihoods available by typing `lik_` and tab to complete.

**Comment by pcarbo** [comment]
I'm going to leave this issue open for now; addressing this Issue will break a lot of people's code, so it is perhaps better to address this issue in a separate branch and combine with other improvements to the ashr interface (e.g., branch `interface-improvements`).

**Comment by stephens999** [comment]
it would be worth knowing who has used this option (as we have not
really documented it - eg with a vignette)
Maybe me and mengyin are the only ones?

matthew

On Mon, Jan 23, 2017 at 10:56 AM, Peter Carbonetto <notifications@github.com

**Comment by pcarbo** [comment]
I will make this change as soon as Mengyin completes her pull request. It affects about 100 lines of code so should be fairly easy to fix.

**Comment by pcarbo** [comment]
See release v2.1-7.
