### ISSUE TITLE
Mosek documentation updates

### ISSUE THREAD

**Issue by pcarbo** [stephens999/ashr#53]
+ [x] Fix links to the Mac-specific and Linux-specific instructions for installing mosek and rmosek.
+ [ ] Post warning about expiry of mosek license (it is only valid for 1 year).

**Comment by stephens999** [comment]
can i bump this @pcarbo 

do you think we can check for license?
and post link to somethign like
https://github.com/stephens999/ashr/blob/master/inst/rmosek-mac.md
if it doesn't exist?

**Comment by pcarbo** [comment]
An initial check that MOSEK is working has been implemented before running `REBayes:KWDual`.

**Comment by pcarbo** [comment]
@stephens999 Yes, this also relates to open Issue #77. I will take care of this soon.
