### ISSUE TITLE
problems with poisson likelihood and mode=0

### ISSUE THREAD

**Issue by stephens999** [stephens999/ashr#68]
@mengyin i get an error with this:
set.seed(100)
l = rexp(1)
x = rpois(100,lambd=l)
ashr::ash(rep(0,100),1,lik=ashr::lik_pois(x))
ashr::ash(rep(0,100),1,lik=ashr::lik_pois(x),mode=0)

**Comment by mengyin** [comment]
Thanks for the example! I just sent a pull request to fix this issue.
