### ISSUE TITLE
installing package ashr

### ISSUE THREAD

**Issue by rfluss** [stephens999/ashr#7]
Hello,
I tried installing the package as shown in the ReadMe 
library(devtools)
install_github("stephens999/ashr")
But it fails to install it.
can you please help me?
Thank you
Ronen

**Comment by stephens999** [comment]
Can you give more details. Eg Sessioninfo and errors you get

**Comment by stephens999** [comment]
Do you have a working c++ compiler on your system?

**Comment by rfluss** [comment]
Thank you for responding,
I dont have a c++ compiler.
I will send the output I get this evening.

Ronen

**Comment by stephens999** [comment]
the easiest way to proceed would be to find a machine with a working c++ compiler installed. eg linux (or possibly mac). I don't use windows, so I'm not really sure what the best way to proceed is there,
but it is possible that installing Rtools (which apparently includes a c++ compiler) would be the easiest way to go. Here's a link:
https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

**Comment by rfluss** [comment]
Thank you!!
I think it managed to install it now

Ronen

**Comment by rfluss** [comment]
Dear  prof stephens,
I tried the simulation you bring in your paper on github.
but the results I get are very different.

The model seems very simple so I dont understand why.
can you have a short look to see if i am mistaken?

Thank you!

attaching my program

The creation of data is only:

n0=     200
n1=     200
beta =  c(rep(0,n0),rnorm(n1))   # H0: b=0, H1:b~N(0,1)
sei =   rep(c(1,10,1,10),c(n0/2,n0/2,n1/2,n1/2))
bi  =   rnorm(n,beta,sei)      # b_hat~N(beta,sei)
zi=     bi/sei                 # z -vaues
pi=     2*(1-pnorm(abs(zi)))   # p-values

**Comment by stephens999** [comment]
i'm on vacation right now. but i took a quick look at your simulation.
but i didn't see any results. so i wondered what you meant by "the results
are very different".

is there a particular figure you are trying to recreate?

Matthew

**Comment by rfluss** [comment]
Thank you!
Sorry for disturbing your vacation.
I am attaching the explanation of simulation with the results
I think its the scenario you described in your paper.
when you finish your vacation I hope you can have a look

thanks again
Ronen

**Comment by stephens999** [comment]
I don't see any attachment...
