### ISSUE TITLE
Pruning g for flash

### ISSUE THREAD

**Issue by willwerscheid** [stephens999/ashr#91]
I am not so sure that we want to prune g for flash. For one, flash doesn't use comp_postprob, etc, so there is no issue with data "lining up." More importantly, though, it makes warmstarts much less effective. If, for example, g gets pruned to a single mixture component (well, not really a mixture anymore), then it will be effectively fixed for eternity if warmstarts are used. A real example: g for factor 1 gets pruned to the single component Unif[0, 5.3]. After factors 2-5 are fit, some of the loadings on the first factor would normally be re-estimated to be somewhat larger than 5.3, but initializing g at Unif[0, 5.3] causes them to be truncated; these effects cascade and we get a very suboptimal backfit.

**Comment by stephens999** [comment]
interesting... and yes, i agree in this case pruning is a problem.
Matthew

**Comment by willwerscheid** [comment]
Another thing I would like to have (and this is related to the problem of using `ashr` with `flashr`) is to be able to pass in a grid not as a fixed grid but as a subgrid which can be expanded if necessary. For example, we could calculate the grid as usual (using `autoselect_mixsd`) but only keep sds that are sufficiently different from from the sds in the subgrid and then combine the two sets of sds. This would guarantee a solution with a better likelihood while also being able to overcome poor initializations of `g`.
